# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

#AYP 17
"""

import time
lista = list(range(10000000))
inicio = time.time()
[valor * 2 for valor in lista]
print("Tiempo de ejecución con listas: ", time.time() - inicio)

import numpy as np
arreglo = np.arange(10000000)
inicio = time.time()
arreglo * 2
print("Tiempo con ejecución con listas: ", time.time() - inicio)

#para importar las librerias siempre es ! y el nombre de la librería a importar
!pip install numpy

import numpy as np
arreglo=np.array([1,2,3,4])
print(arreglo)

print("El número de dimensiones del arreglo es:", arreglo.ndim)
print("La forma del arreglo es: ", arreglo.shape)
print("El total de elementos de arreglo es: ", arreglo.size)
print("Los tipos de datos en el arreglo son: ", arreglo.dtype)

arreglo_2d = np.array([[1,2,3],[4,5,6]])
print(arreglo_2d)
print("El número de dimensiones del arreglo es:", arreglo_2d.ndim)
print("La forma del arreglo es: ", arreglo_2d.shape)
print("El total de elementos de arreglo es: ", arreglo_2d.size)
print("Los tipos de datos en el arreglo son: ", arreglo_2d.dtype)

arreglo_3d = np.array([[[3,1,6],[2,9,4],[2,4,5]]])
print(arreglo_3d)
print("El número de dimensiones del arreglo es:", arreglo_3d.ndim)
print("La forma del arreglo es: ", arreglo_3d.shape)
print("El total de elementos de arreglo es: ", arreglo_3d.size)
print("Los tipos de datos en el arreglo son: ", arreglo_3d.dtype)

ceros=np.zeros((2,3))
print(ceros)

unos=np.ones((3,2))
print(unos)

vacio=np.empty((5,6))
print(vacio)

np.arange(0,10,2)

np.linspace(0,1,5)

arreglo1=np.array([[1,0],[-1,1]])
print(arreglo1)

arreglo1 / 0

arreglo2=np.array([[np.inf, np.nan]])
print(arreglo2)

array_inf=np.array([1,2.5])**5
array_inf