# -*- coding: utf-8 -*-
"""Copia de Te damos la bienvenida a Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14teV6J5C_OnymfoSBMjVPOMlz7tFbUHu

#Introducción a Pandas

Es una librería, se debe instalar e importar con:
!pip install pandas/!import pandas as pd
"""

!pip install pandas

import pandas as pd

"""**Los dataframes**"""

pd.DataFrame(data=[(0,1,2), (1,2,3), (2,3,4), (3,4,5), (2,3)])

diccionarios = {'curso1':[10,5,33,42,25,22],
                'curso2':[0,15,21,30,31,11],
                'curso3': [1,2,3,4,6,4],
                'curso4': [52,70,2,45,85,14]}

pd.DataFrame(data=diccionarios)

import numpy as np

matriz = np.arange(9).reshape(3,3)

matriz

indice = ('enero', 'febrero', 'marzo','abril','mayo','junio')

cursos = pd.DataFrame(data=diccionarios, index=indice)
cursos

pd.DataFrame(matriz, index=['uno','dos','tres'],columns=['a','b','c'])

cursos['curso3']

cursos[['curso3','curso4']]

type(cursos['curso3'])

datos_np=np.arange(1,13).reshape(3,4)

datos_np

datos=pd.DataFrame(datos_np)
datos

datos[2]

cursos[:1]

cursos[::2]

cursos['marzo':'mayo']

cursos['curso1'][2]

cursos['curso1']['marzo']

cursos['curso2'][3:5]

pd.Series([12,4,32,41,33,28], name='py201')

serie=pd.Series([12,4,32,41,33,28], index=indice, name='py201')
serie

"""**Operaciones básicas con Pandas**"""

import pandas as pd
import numpy as np
from datetime import datetime

indice = ['gerente', 'supervisor', 'vendedor', 'cajero']
personal = pd.DataFrame({'nombres':('Juan Pérez',
                                    'María Sánchez',
                                    'Jorge Vargas',
                                    'Rodrigo Martínez'),
            'fechas':(datetime(1995,12,21),
                      datetime(1989,1,13),
                      datetime(1992,9,14),
                      datetime(1993,7,8)),
            'saldo': (2500,
                      5345,
                      np.nan,
                      11323.2),
            'al corriente':(True,
                            True,
                            False,
                            True)}, index=indice)

personal

#.shape es para saber como es la forma
personal.shape

#.index es para que nos entregue los nombres de los índices (filas)
personal.index

#.columns nos entrega los valores de las columnas
personal.columns

personal.reset_index()
personal

personal.set_index('nombres')

personal.info()

datos = pd.DataFrame(np.arange(20).reshape(5,4),
                     columns=('primero','segundo','tercero','cuarto'))
datos

datos.iloc[2,[3]]
#esto nos entrega una serie

#para valor numerico debe ser:
datos.iloc[2,3]

#el metodo loc nos permite igualmente localizar los datos, pero utilizando los nombres
personal.loc['supervisor',['fechas']]

personal.loc['gerente', ['fechas','nombres']]

personal['saldo']>3000

personal.loc[personal ["saldo"]>3000]

personal.loc[personal["al corriente"]]

personal.loc[personal["al corriente"]==False]

"""# Operaciones de integración"""

indice_1 = ("lunes", "martes", "miércoles")

marco_1 = pd.DataFrame({'Centro':[1520,1640,1043],

                       'Sur':[1422,1673,1534],

                      'Oriente':[1021,1073,1100]},

                       index=indice_1)
marco_1

indice_2 = ("jueves", "viernes", "sábado")
marco_2 = pd.DataFrame({'Centro':[1321,1459,1875],
                       'Sur':[1622,1841,1920],
                      'Oriente':[1500,1432,1491]},
                      index=indice_2)
marco_2

pd.concat([marco_1, marco_2])



pd.concat([marco_1, marco_2], axis=1)



pd.concat([marco_1, marco_2], axis=1)['Centro']